config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'books#index'

  # get '/books/new_with_cover_photo'
  resources :books do

    # non-RESTful routes can be specified in a block
    # post '/check_out', to: 'books#check_out', as: 'check_out_book'
  end

  # or you can type them out manually
  # post '/books/:id/check_out', to: 'books#check_out', as: 'check_out_book'


  resources :authors do
    resources :books, only: [:index, :new]
  end

  get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  # Or, you can restrict what you want with :only or :except
  # resources :books, only: [:index, :new, :create]
  # resources :authors, except: [:destroy]

  get "/auth/:provider/callback", to: "sessions#create", as: 'auth_callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books # plural


  def first_published
    my_books = self.books.where.not(publication_year: nil)
    my_books = my_books.order(publication_year: :asc)

    if my_books.length == 0
      return nil
    end

    first_book = my_books.first

    return first_book.publication_year
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author # singular
  has_and_belongs_to_many :genres

  validates :title, presence: true, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books

  # validation on name
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private
  # Check that the user is logged in, and send back
  # an error if they are not
  # Store the looked-up user in @user in case
  # someone wants to use it later.
  # We write this method here so it will be available
  # in _all_ controllers
  def require_login
    @user = User.find_by(id: session[:user_id])
    head :unauthorized unless @user
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.new(author_params)
    if author.save
      redirect_to authors_path
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    author = Author.find(params[:id])
    author.assign_attributes(author_params)
    if author.save
      redirect_to author_path(author)
    end
  end

  def destroy
    Author.destory(params[:id])
  end

  private
  def author_params
    return params.require(:author).permit(:name, :bio)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :update, :destroy]

  # Use a controller filter to manage authorization
  # require_login is a method we wrote in the ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    if params[:author_id]
      # Have an author id
      @author = Author.find(params[:author_id])
      @books = @author.books
      # - or -
      # @books = Book.where(author_id: params[:author_id])
    else
      # No author, load all the books
      # This is our old, non-nested version
      @books = Book.all
    end
  end

  def new
    @book = Book.new(author_id: params[:author_id])
  end

  def create
    # Rails form_for creates a nested param structure
    # This is fancy and good, but means we need to do
    # a little extra work.
    @book = Book.new(book_params)

    # Could also say:
    # book.title = params[:book][:title]

    if @book.save
      # redirect_to '/books'
      flash[:success] = "Book added successfully"
      redirect_to books_path
    else
      # Validations failed! What do we do?
      # This flash message is redundant but for demonstration purposes
      flash.now[:failure] = "Validations Failed"
      render :new, status: :bad_request
    end
  end

  def show; end

  def edit; end

  def update
    # Or we can do it all together with assign_attributes
    @book.assign_attributes(book_params)

    # Arbitrary rule: always use assign_attributes,
    # not update. This will pay off later.

    if @book.save
      redirect_to book_path(@book)
    else
      render :edit, status: :bad_request
    end
  end

  def destroy
    # find it first
    # check the result of destroy
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    return params.require(:book).permit(:title, :author_id, :synopsis, :publication_year, genre_ids: [])
  end

  def find_book
    # use find_by(id:) instead of find
    # @book will be nil if the find_by failed
    @book = Book.find_by(id: params[:id])
    # head is similar to render, except it doesn't run
    #   a view template, so the browser only gets the status code
    # This is not the only thing you can do in this scenario
    #   but it is the simplest
    head :not_found unless @book
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @author = Author.new
  end

  def create
    auth_hash = request.env['omniauth.auth']

    if auth_hash['uid']
      @user = User.find_by(uid: auth_hash[:uid], provider: 'github')
      if @user.nil?
        # User doesn't match anything in the DB
        # Attempt to create a new user
        @user = User.new(
          name: auth_hash['info']['name'],
          email: auth_hash['info']['email'],
          uid: auth_hash['uid'],
          provider: auth_hash['provider'])
        if @user.save
          # saved successfully
          session[:user_id] = @user.id
          flash[:success] = "Logged in successfully"
          redirect_to root_path
        else
          # not saved successfully
          flash[:error] = "Could not log in"
          redirect_to root_path
        end

      else
        session[:user_id] = @user.id
        flash[:success] = "Logged in successfully"
        redirect_to root_path
      end
    else
      flash[:error] = "Could not log in"
      redirect_to root_path
    end

    # author = Author.find_by(name: params[:author][:name])
    #
    # if author
    #   session[:author_id] = author.id
    #   flash[:success] = "#{ author.name } is successfully logged in."
    #   redirect_to root_path
    # else
    #   # other logic that does more stuff
    # end
  end

  def destroy
    # session[:author_id] = nil
    session.delete(:user_id)
    flash[:success] = "Logged out successfully."

    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_date(date)
    ("<span class='date'>" + date.strftime("%A, %b %d") + "</span>").html_safe
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/authors/_form.html.erb
<%= render partial: "layouts/error_messages", locals: { model: @author } %>

<%= form_for @author do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>




<div>
  <%= f.label :bio %>
  <%= f.text_area :bio %>
</div>

<div>
  <%= f.submit %>
</div>
<% end %>

app/views/authors/edit.html.erb
<%= render partial: "form" %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<ul>
  <% @authors.each do |author| %>
  <li>
    <strong>
      <%= link_to author.name, author_path(author) %>
    </strong>
    <%= link_to "Edit", edit_author_path(author) %>
    <%= link_to("Delete", author_path(author), method: :delete, data: { confirm: "Really really?" }) %>
  </li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<%= render partial: "form" %>

app/views/authors/show.html.erb
<h2><%= @author.name %></h2>

<p><%= @author.bio %></p>

<section>
  <h3>Bibliography</h3>
  <p>This author was first published <%= @author.first_published %></p>

  <ul>
    <% @author.books.each do |book| %>
    <li>
      <%= link_to book.title, book_path(book) %>
      <% if book.publication_year %>
        (<%= book.publication_year %>)
      <% end %>
    </li>
    <% end %>
  </ul>
</section>

<p>Created at: <%= readable_date @author.created_at %></p>

app/views/books/_form.html.erb
<h4>
  <% page_title ||= "Cool Page You Made" %>
  <%= page_title %>
</h4>

<%= render partial: "layouts/error_messages", locals: { model: @book } %>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <!--
  Only show the author dropdown if we don't
  already have one. Is this acutally good UX
  design? Depends on the application!
  -->
  <% unless @book.author_id %>
    <%= f.label :author, "Auttttthor" %>
    <%= f.select :author_id, Author.all.map{ |auth| [auth.name, auth.id] } %>
  <% else %>
    <%= f.hidden_field :author_id %>
  <% end %>

  <%= f.label :publication_year %>
  <%= f.number_field :publication_year %>

  <%= f.label :synopsis %>
  <%= f.text_area :synopsis %>

  <div>
  <%= f.label :genres %>
  <%= collection_check_boxes(:book, :genre_ids, Genre.all, :id, :name) %>
  </div>

  <%= f.submit class: "button" %>
<% end %>

app/views/books/index.html.erb
<!-- <h2>Welcome to the Octos Library!</h2> -->

<p>
  We have many books
  <% if @author %>
    by <%= @author.name %>
  <% end %>
  sitting around for your reading pleasure
</p>

<ul>
<% @books.each do |book| %>
  <li>
    <strong><%= link_to(book.title, book_path(book)) %></strong>

    By: <%= book.author.name %>
    <!-- <a href="/books/#{book.id}">Go to it now!</a> -->

    <%= link_to("Edit", edit_book_path(book)) %>
    <%= link_to("Delete", book_path(book.id), method: :delete, data: { confirm: "Are you sure you want to delete Book #{ book.title }?" }) %>

    <%= link_to("Go find it on google", "http://www.google.com/search?q=#{book.title}") %>
  </li>
<% end %>
</ul>


<%= link_to("Add a New Book", new_book_path, class: "important") %>

<!-- <a href="/books/new" class="important">Add a New Book</a> -->

app/views/books/new.html.erb
<%= render partial: "form", locals: { page_title: "Create a new book"} %>

app/views/books/show.html.erb
<h2>Details for book <%= @book.title %></h2>
<p>Author <%= @book.author.name %></p>
<p>Published: <%= @book.publication_year %></p>
<p>Synopsis: <%= @book.synopsis %></p>
<%= link_to "Edit this book", edit_book_path(@book) %>
<p>Genres:</p>
<ul>
  <% @book.genres.each do |genre| %>
    <li>
      <%= genre.name %>
    </li>
  <% end %>
</ul>

app/views/layouts/_error_messages.html.erb
<% if model.errors.messages.any? %>
  <section class="alert callout">
    <h3>There were some problems</h3>
    <ul>
      <% model.errors.messages.each do |field, problems| %>
        <% problems.each do |problem| %>
          <li>
            <strong><%= field %></strong>
            <%= problem %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Octos Library" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header>
      <h1>
        <%= image_tag "books-icon.png", alt: "Site logo", class: "logo" %>
        Welcome to the Octos Library
      </h1>
      <nav>
        <ul>
          <li><%= link_to "All books", books_path, class: "hollow button" %></li>
          <li><%= link_to "New book", new_book_path, class: "hollow button" %></li>
          <li><%= link_to "All authors", authors_path, class: "hollow button" %></li>
          <li><%= link_to "New author", new_author_path, class: "hollow button" %></li>

          <li>
            <% if session[:user_id] %>
              <%= link_to "Logout", logout_path, method: :delete, class: "hollow button" %>
            <% else %>
              <%= link_to "Login", "/auth/github", class: "hollow button" %>
            <% end %>
          </li>
        </ul>
      </nav>
    </header>

    <main>
      <section class="flash">
        <% flash.each do |name, message| %>
          <div class="<%= name %>"><%= message %></div>
        <% end %>
      </section>

      <%= yield %>
    </main>

    <footer>
      <p>&copy; Ada Developers Academy, 2018</p>
    </footer>

  </body>
</html>